#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("meetfriends.Resource", IsApplication=true)]

namespace meetfriends
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int slide_right = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int slide_up = 2131034113;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonSignUpStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSingInStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int EditTextStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ProgressBarStyle = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int btnDialogEmail = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int btnSignIn = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int btnSignUp = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int progressBar1 = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int relativeLayout1 = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int txtCreateAccount = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int txtEmail = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int txtFirstName = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int txtPassword = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int DialogSignIn = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int DialogSignUp = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int dialog_animation = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
